name: news_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  equatable: ^2.0.5
  flutter_modular: ^6.3.2
  google_fonts: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  iconsax: ^0.0.8
  uno: ^1.1.9
  asp: ^1.3.0
  headline:
    path: packages/headline
  fav_grab:
    path: packages/fav_grab
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
